### ISSUE TITLE
Software inconsistent after "git pull"

### ISSUE THREAD

**Issue by SteffenIvanhoe** [chaeplin/dashmnb#55]
For the necessary masternode restart after the 12.2 version I made a `git pull `in "dashmnb" directory. It seemed to go without problem. But when calling the script with `python bin\dashmnb.py -a` I get the following error:

```
[masternodes config]
        configured : 1
        passed     : 1

---> get masternodelist : status
---> get masternodelist : addr

[masternodes status]
Traceback (most recent call last):
  File "bin\dashmnb.py", line 425, in <module>
    main(args)
  File "bin\dashmnb.py", line 106, in main
    print_mnstatus(mn_config, mns, mna)
  File "bin\..\dashlib\mnb_misc.py", line 131, in print_mnstatus
    mnj = get_dashninja(mn_config)
  File "bin\..\dashlib\mnb_misc.py", line 112, in get_dashninja
    if status_ninja.get('status') == 'OK':
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by chaeplin** [comment]
There was an error on dashninja.

error handlinf added.
https://github.com/chaeplin/dashmnb/commit/3c3422af23620f324124a7d6525fceb15b20a5c1

```
optional arguments:
  -h, --help            show this help message and exit
  -c, --check           check masternode config
  -s, --status          show masternode status
  -a, --anounce         anounce missing masternodes
  -b, --balance         show masternodes balance
  -y, --voteyes         vote Yes to a proposal using all mns
  -n, --voteno          vote No to a proposal using all mns
  -f, --voteabstain     vote Abstain to a proposal using all mns
  -q, --votequery       get vote status on a proposal by all mns
  -l, --showall         show all configured masternodes
  -m, --maketx          make signed raw tx
  -x, --xfer            broadcast signed raw tx
  -w, --whale           do not ask yes or no, all yes
  -o, --badge           Sign message for Masternode Owner/Operator badge
  -k, --skip            skip version and explorer checking


	version  : 0.6.1
	caller   : <module>
	function : parse_args
	===> print help
```
